### ISSUE TITLE
CardView 모듈화

### ISSUE THREAD

**Issue by SJ-Kwak** [sdp-tech/SASM_Mobile#78]
## Description
- 슬라이드 카드바 모듈화

## To-Do
- [x] 모듈 생성

**Comment by dgfh0450** [comment]
참고: 
https://velog.io/@2ast/React-Native-%EC%BA%90%EB%9F%AC%EC%85%80-%EB%A7%8C%EB%93%A4%EA%B8%B0-feat.-ScrollView
https://deemmun.tistory.com/m/68
